### ISSUE TITLE
compiltion of gadgetron 4.0 failed

### ISSUE THREAD

**Issue by valeryozenne** [gadgetron/gadgetron#741]
Hi David,

Following the wiki, I try to compile on a ubuntu 18.04  with gcc 6.5, here  (please find the file enclosed) the log of the cmake and make command

/home/imagerie/Dev/gadgetron4.0/toolboxes/core/vector_td.h:130:47: error: specialization of \u2018template<class _Tp> class std::tuple_size\u2019 in different namespace [-fpermissive]
 template <class T, unsigned int N> class std::tuple_size<Gadgetron::vector_td<T, N>> : public std::integral_constant<size_t, N> {};

Any idea ?

Thanks in advance 

Best

Valéry

[debug.txt](https://github.com/gadgetron/gadgetron/files/3211848/debug.txt)

**Comment by dchansen** [comment]
Hi Valery,

This is actually a bug in gcc 6.5, but the default gcc on Ubuntu 18.04 is 7.4, which also works with CUDA 10.1. 

Best,
David
