### PR TITLE
Gadgetron Matlab Related

### PR DESCRIPTION
**Pull request by ojosephs**
Here's a horrible, big pull request including several unrelated topics. I'm sorry but don't know how to break it down. The changes to different files are more or less independent modifications. Comments file by file, as follows:

apps/gadgetron/Gadget.h
All of these changes relate to issue #196.
Allowing multi word strings as gadget parameters.

gadgets/epi/CMakeLists.txt
gadgets/epi/EPIPackNavigatorGadget.h
gadgets/epi/EPIPackNavigatorGadget.cpp
New gadget for packing EPI reference navigator echoes into the epi echo train data.
Workaround for getting navigator data (and epi data) efficiently into Matlab using the existing MatlabBufferGadget. (For me would be better to have the navigator data passed independently, in an analogous manner to reference data.)

gadgets/matlab/BaseBufferGadget.m
Commented out slow header translation code. Headers were unnecessary for our applications. But speed was necessary(!)
Fix for accessing data. (Line 62/63).

gadgets/matlab/MatlabBufferGadget.cpp
Attempt to introduce mutex's for running multiple matlab gadgets in the same chain. Not sure if effective, but at least a single matlab gadget does work completely stably with this code for our applications.
Memory leak fix (Line 103/110).

gadgets/matlab/MatlabBufferGadget.h
Allow for Matlab startup command to be specified as gadget parameter. (Issue #196)

gadgets/mri_core/AcquisitionAccumulateTriggerGadget.cpp
Allow for embedded reference data for grappa. (Multi-echo flash application.)

toolboxes/matlab/CMakeLists.txt
toolboxes/matlab/MatlabUtils.cpp
Workaround for compilation errors related to commit 40618e433290bc3e8ca504d27d32dfc803ccb282

### CODE REVIEW

**Comment by hansenms** [comment]
Hi @ojosephs,

Thanks for putting this together. A few issues:

These commits break the Matlab integration tests:

`${GADGETRON_SOURCE}/test/integration/cases/matlab.cfg`
`${GADGETRON_SOURCE}/test/integration/cases/matlab_ideal.cfg`

due to the changes related to the unpacking of the headers. I think if you want to get rid of that, you need to make a new Gadget and not break the existing one. 

Please make sure that all integration tests pass on PRs. It is easy to run them:

    cd ${GADGETRON_SOURCE}/test/integration
    python get_data.py
    python run_all_tests.py test_cases.txt

Or to just run the Matlab test:

    python run_gadgetron_test.py cases/matlab.cfg 

Also, could you squash all the commits into one (or a few commits). We should aim to have all commits pass tests and intermediate commits can be squashed (use `git rebase -i master` after pulling a clean master) to make the revision history a bit easier to navigate. 

Thanks,
Michael

**Comment by ojosephs** [comment]
Thanks for the advice. Am closing this pull request and opening a new, rebased, one with squashes and integration tested.

Oliver
