### ISSUE TITLE
Cannot Compile GT

### ISSUE THREAD

**Issue by ahsanjav** [gadgetron/gadgetron#887]
GT won't compile  with [build] /opt/code/gadgetron/toolboxes/core/cpu/math/hoNDArray_reductions.cpp:3:10: fatal error: range/v3/core.hpp: No such file or directory

**Comment by ahsanjav** [comment]
Was able to fix that by installing librange-v3-dev but then get more errors. 

 /opt/code/gadgetron/toolboxes/core/cpu/hoNDArray_utils.h:1015:121: error: cannot deduce template arguments for 'logical_and' from ()
[build]        bool all_dimensions_valid = ranges::accumulate(arrays | view::transform(dimensions_valid), true, std::logical_and() );
[build]                                                                                                                          ^
[build] /opt/code/gadgetron/toolboxes/core/cpu/hoNDArray_utils.h:1020:61: error: 'views' has not been declared
[build]        const size_t inner_stride = ranges::accumulate(dims | views::slice(size_t(0), dimension),
[build]                                                              ^~~~~
[build] /opt/code/gadgetron/toolboxes/core/cpu/hoNDArray_utils.h:1021:81: error: cannot deduce template arguments for 'multiplies' from ()
[build]                                                       size_t(1), std::multiplies());

**Comment by deepdumbo** [comment]
I got exactly the same errors as ahsanjav. First, I got error: "range/v3/core.hpp: No such file or directory". Then, I installed librange-v3-dev, and got error: "'views' has not been declared". Thanks!

**Comment by dchansen** [comment]
Gadgetron compiles on Ubuntu 20.04 , as per the build tests. Are you on Ubuntu 18.04, or something more exotic?

**Comment by aprillassie** [comment]
Hi, I had the same issue. And yes, I'm on Ubuntu 18.04. Any suggestions to solve it? Thanks!!

**Comment by ahsanjav** [comment]
Thanks @dchansen : I was using 18.04 just tested on 20.04 and it compiles just fine.

**Comment by aTrotier** [comment]
The main issue is that the docker image + CUDA is built from 18.04. I did not try but the gadgetron compilation might also fail in it

**Comment by ahsanjav** [comment]
I tried the docker image and it failed - I was however using an older version with updates done along the way to keep up with GT. 

I also tried to modify the docker file because Nvidia now provides 2004 docker images but it failed to launch - still debugging this one - I may wait for it to be pushed from GT. 

A solution could be to take the 18.04 container and just run an upgrade on it - I have tested this and it works . Hope that helps.

**Comment by aTrotier** [comment]
I'm also trying to create a working docker with the 
`nvidia/cuda:11.0-devel-ubuntu20.04`

**Comment by aTrotier** [comment]
Compilation works with that dockerfile. I still have to try the integration test :
```
FROM nvidia/cuda:11.0-devel-ubuntu20.04

# Proxy issue ->
# ENV http_proxy="http://192.168.10.1:3128"

RUN apt-get update --quiet
RUN DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata
RUN    apt-get install --no-install-recommends --no-install-suggests --yes  \
     software-properties-common apt-utils wget build-essential cython3  python3-dev python3-pip \
      libhdf5-serial-dev cmake git-core libboost-all-dev libfftw3-dev h5utils jq hdf5-tools \
       liblapack-dev libatlas-base-dev libxml2-dev libfreetype6-dev pkg-config libxslt-dev \
       libarmadillo-dev libace-dev gcc-multilib libgtest-dev liblapacke-dev libplplot-dev libdcmtk-dev supervisor supervisor net-tools cpio libpugixml-dev jove libopenblas-base libopenblas-dev libpugixml-dev vim cmake-curses-gui

 RUN apt-get install \
     make \
     libhdf5-dev



 RUN pip3 install -U pip setuptools
 RUN pip3 install numpy scipy Cython tk-tools matplotlib scikit-image opencv_python pydicom scikit-learn sympy
 RUN apt-get install --no-install-recommends --no-install-suggests --yes python3-psutil python3-lxml python3-pil python3-h5py
 RUN DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --no-install-suggests --yes python3-tk

 RUN pip3 install torch==1.4.0+cpu torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html

# for embedded python plot, we need agg backend
RUN mkdir -p /root/.config/matplotlib && touch /root/.config/matplotlib/matplotlibrc 
RUN echo "backend : agg" >> /root/.config/matplotlib/matplotlibrc




# Install MKL  
RUN cd /tmp && \
   wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB && \
   apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB && \
   sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list' && \
   apt-get update && \
   apt-get install --yes intel-mkl-64bit-2018.2-046 && \
   update-alternatives --install /usr/lib/x86_64-linux-gnu/libblas.so     libblas.so-x86_64-linux-gnu      /opt/intel/mkl/lib/intel64/libmkl_rt.so 150 && \
   update-alternatives --install /usr/lib/x86_64-linux-gnu/libblas.so.3   libblas.so.3-x86_64-linux-gnu    /opt/intel/mkl/lib/intel64/libmkl_rt.so 150 && \
   update-alternatives --install /usr/lib/x86_64-linux-gnu/liblapack.so   liblapack.so-x86_64-linux-gnu    /opt/intel/mkl/lib/intel64/libmkl_rt.so 150 && \
   update-alternatives --install /usr/lib/x86_64-linux-gnu/liblapack.so.3 liblapack.so.3-x86_64-linux-gnu  /opt/intel/mkl/lib/intel64/libmkl_rt.so 150 && \
   echo "/opt/intel/lib/intel64"     >  /etc/ld.so.conf.d/mkl.conf && \
   echo "/opt/intel/mkl/lib/intel64" >> /etc/ld.so.conf.d/mkl.conf && \
   ldconfig && \
   echo "MKL_THREADING_LAYER=GNU" >> /etc/environment

#ZFP
RUN mkdir /opt/code
RUN cd /opt/code && \
    git clone https://github.com/hansenms/ZFP.git && \
    cd ZFP && \
    mkdir lib && \
    make && \
    make shared && \
    make -j $(nproc) install


#Set more environment variables in preparation for Gadgetron installation
ENV GADGETRON_HOME=/usr/local \
    ISMRMRD_HOME=/usr/local

ENV PATH=$PATH:$GADGETRON_HOME/bin:$ISMRMRD_HOME/bin:/usr/local/cuda/bin \
    LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ISMRMRD_HOME/lib:$GADGETRON_HOME/lib:/usr/local/lib64 \
    LIBRARY_PATH=$LIBRARY_PATH:/usr/local/cuda/lib64/stubs

#ISMRMRD
ARG ISMRMRD_URL=https://github.com/ismrmrd/ismrmrd.git
ARG ISMRMRD_COMMIT=27a7c58

RUN echo ${ISMRMRD_URL}
RUN cd /opt/code && \
    pwd && ls -l /opt/ && \
    git clone ${ISMRMRD_URL} && \
    echo ${ISMRMRD_COMMIT} && \
    pwd && ls -l /opt/code && \
    cd ismrmrd && \ 
   # git checkout ${ISMRMRD_COMMIT} && \
    mkdir build && \
    cd build && \
    cmake ../ && \
    make -j $(nproc) && \
    make install

RUN apt-get install --yes librange-v3-dev
#GADGETRON
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda:/usr/local/cuda/lib64 
ARG GADGETRON_URL=https://github.com/gadgetron/gadgetron.git
ARG GADGETRON_COMMIT=7bbf633
RUN cd /opt/code && \
    git clone ${GADGETRON_URL} && \
    cd gadgetron && \
   # git checkout ${GADGETRON_COMMIT} && \
    mkdir build && \
    cd build && \
    cmake .. -DUSE_MKL=ON -DBUILD_SUPPRESS_WARNINGS=ON && \
    make -j $(nproc) && \
    make install && \
    /opt/code/gadgetron/docker/manifest --key .io.gadgetron.gadgetron.sha1 --value `git rev-parse HEAD` && \
    cp /opt/code/gadgetron/docker/start_supervisor /opt/ && \
    cp /opt/code/gadgetron/docker/supervisord.conf /opt/

#SIEMENS_TO_ISMRMRD
ARG SIEMENS_TO_ISMRMRD_URL=https://github.com/ismrmrd/siemens_to_ismrmrd.git
ARG SIEMENS_TO_ISMRMRD_COMMIT=11cf24b
RUN cd /opt/code && \
    git clone ${SIEMENS_TO_ISMRMRD_URL} && \
    cd siemens_to_ismrmrd && \
    # git checkout ${SIEMENS_TO_ISMRMRD_COMMIT} && \
    mkdir build && \
    cd build && \
    cmake ../ && \
    make -j $(nproc) && \
    make install && \
    /opt/code/gadgetron/docker/manifest --key .io.gadgetron.siemens_to_ismrmrd.sha1 --value `git rev-parse HEAD` 
```

**Comment by ahsanjav** [comment]
Thank you for sharing this. I was able to compile in release mode just fine but failed in debug mode. Were you able to compile in debug mode using this image ?

**Comment by aTrotier** [comment]
Not working for me neither :/

**Comment by hansenms** [comment]
@aTrotier, @ahsanjav, @dchansen wanted to pick up this thread. I am seeing a bunch of the "cannot deduce template arguments for ..." errors, I believe related to librange. Is it supposed to work?

**Comment by aTrotier** [comment]
@hansenms We are using this base on our server, it works in standard compilation. I did not try in debug mode.

```
FROM nvidia/cuda:11.0-devel-ubuntu20.04

RUN apt-get update --quiet
RUN DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata zsh
RUN    apt-get install --no-install-recommends --no-install-suggests --yes  \
     software-properties-common apt-utils wget build-essential cython3  python3-dev python3-pip \
      libhdf5-serial-dev cmake git-core libboost-all-dev libfftw3-dev h5utils jq hdf5-tools \
       liblapack-dev libatlas-base-dev libxml2-dev libfreetype6-dev pkg-config libxslt-dev \
       libarmadillo-dev libace-dev gcc-multilib libgtest-dev liblapacke-dev libplplot-dev libdcmtk-dev supervisor supervisor net-tools cpio libpugixml-dev jove libopenblas-base libopenblas-dev libpugixml-dev vim cmake-curses-gui

 RUN apt-get install \
     make \
     libhdf5-dev



 RUN pip3 install -U pip setuptools
 RUN pip3 install numpy scipy Cython tk-tools matplotlib scikit-image opencv_python pydicom scikit-learn sympy multimethod pyxb
 RUN apt-get install --no-install-recommends --no-install-suggests --yes python3-psutil python3-lxml python3-pil python3-h5py
 RUN DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --no-install-suggests --yes python3-tk

 RUN pip3 install torch==1.4.0+cpu torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html

# for embedded python plot, we need agg backend
RUN mkdir -p /root/.config/matplotlib && touch /root/.config/matplotlib/matplotlibrc 
RUN echo "backend : agg" >> /root/.config/matplotlib/matplotlibrc




# Install MKL  
RUN cd /tmp && \
   wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB && \
   apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB && \
   sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list' && \
   apt-get update && \
   apt-get install --yes intel-mkl-64bit-2018.2-046 && \
   update-alternatives --install /usr/lib/x86_64-linux-gnu/libblas.so     libblas.so-x86_64-linux-gnu      /opt/intel/mkl/lib/intel64/libmkl_rt.so 150 && \
   update-alternatives --install /usr/lib/x86_64-linux-gnu/libblas.so.3   libblas.so.3-x86_64-linux-gnu    /opt/intel/mkl/lib/intel64/libmkl_rt.so 150 && \
   update-alternatives --install /usr/lib/x86_64-linux-gnu/liblapack.so   liblapack.so-x86_64-linux-gnu    /opt/intel/mkl/lib/intel64/libmkl_rt.so 150 && \
   update-alternatives --install /usr/lib/x86_64-linux-gnu/liblapack.so.3 liblapack.so.3-x86_64-linux-gnu  /opt/intel/mkl/lib/intel64/libmkl_rt.so 150 && \
   echo "/opt/intel/lib/intel64"     >  /etc/ld.so.conf.d/mkl.conf && \
   echo "/opt/intel/mkl/lib/intel64" >> /etc/ld.so.conf.d/mkl.conf && \
   ldconfig && \
   echo "MKL_THREADING_LAYER=GNU" >> /etc/environment

#ZFP
RUN mkdir /opt/code
RUN cd /opt/code && \
    git clone https://github.com/hansenms/ZFP.git && \
    cd ZFP && \
    mkdir lib && \
    make && \
    make shared && \
    make -j $(nproc) install


#Set more environment variables in preparation for Gadgetron installation
ENV GADGETRON_HOME=/usr/local \
    ISMRMRD_HOME=/usr/local

ENV PATH=$PATH:$GADGETRON_HOME/bin:$ISMRMRD_HOME/bin:/usr/local/cuda/bin \
    LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ISMRMRD_HOME/lib:$GADGETRON_HOME/lib:/usr/local/lib64 \
    LIBRARY_PATH=$LIBRARY_PATH:/usr/local/cuda/lib64/stubs

#ISMRMRD
ARG ISMRMRD_URL=https://github.com/ismrmrd/ismrmrd.git
ARG ISMRMRD_COMMIT=27a7c58

RUN echo ${ISMRMRD_URL}
RUN cd /opt/code && \
    pwd && ls -l /opt/ && \
    git clone ${ISMRMRD_URL} && \
    echo ${ISMRMRD_COMMIT} && \
    pwd && ls -l /opt/code && \
    cd ismrmrd && \ 
   # git checkout ${ISMRMRD_COMMIT} && \
    mkdir build && \
    cd build && \
    cmake ../ && \
    make -j $(nproc) && \
    make install

RUN apt-get install --yes librange-v3-dev
#GADGETRON
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda:/usr/local/cuda/lib64 
ARG GADGETRON_URL=https://github.com/gadgetron/gadgetron.git
ARG GADGETRON_COMMIT=7bbf633
RUN cd /opt/code && \
    git clone ${GADGETRON_URL} && \
    cd gadgetron && \
   # git checkout ${GADGETRON_COMMIT} && \
    mkdir build && \
    cd build && \
    cmake .. -DUSE_MKL=ON -DBUILD_SUPPRESS_WARNINGS=ON && \
    make -j $(nproc) && \
    make install && \
    /opt/code/gadgetron/docker/manifest --key .io.gadgetron.gadgetron.sha1 --value `git rev-parse HEAD` && \
    cp /opt/code/gadgetron/docker/start_supervisor /opt/ && \
    cp /opt/code/gadgetron/docker/supervisord.conf /opt/

#SIEMENS_TO_ISMRMRD
ARG SIEMENS_TO_ISMRMRD_URL=https://github.com/ismrmrd/siemens_to_ismrmrd.git
ARG SIEMENS_TO_ISMRMRD_COMMIT=11cf24b
RUN cd /opt/code && \
    git clone ${SIEMENS_TO_ISMRMRD_URL} && \
    cd siemens_to_ismrmrd && \
    # git checkout ${SIEMENS_TO_ISMRMRD_COMMIT} && \
    mkdir build && \
    cd build && \
    cmake ../ && \
    make -j $(nproc) && \
    make install && \
    /opt/code/gadgetron/docker/manifest --key .io.gadgetron.siemens_to_ismrmrd.sha1 --value `git rev-parse HEAD` 

RUN pip3 install git+https://github.com/ismrmrd/ismrmrd-python
RUN pip3 install gadgetron

#BART
ARG BART_URL=https://github.com/mrirecon/bart
ARG BART_COMMIT=e1a4303
RUN cd /opt/code && \
    git clone ${BART_URL} && \
    cd bart && \
    # git checkout ${BART_COMMIT} && \
    cd Makefiles && \
    > Makefile.local && \
    echo "CUDA=1" >> Makefile.local && \
    echo "CUDA_BASE = /usr/local/cuda/" >> Makefile.local && \
    echo "MKL=1" >> Makefile.local && \
    echo "MKL_BASE=/opt/intel/mkl" >> Makefile.local && \
    cd .. && \
    make && \
    make install

ENV LC_ALL=C

# Clean up packages.
# RUN  apt-get clean && \
#    rm -rf /var/lib/apt/lists/*

#CMD ["/opt/start_supervisor"]
# CMD ["/bin/bash"]
```

**Comment by dchansen** [comment]
@hansenms 
The 20.04 images build fine on for me. Grabbing the base images from dockerhub and using them as the base for the incremental images is not guaranteed to work.

 I've added a [pull request](https://github.com/gadgetron/gadgetron/pull/900) that automatically builds the 20.04 image with and without CUDA support. You can see the resulting docker images on [my branch](https://github.com/dchansen/gadgetron).

**Comment by hansenms** [comment]
@dchansen understood, the 20.04 images are fine. I should have been more specific. Are 18.04 builds no longer working. If so that is cool with me, but I would suggest kicking out all the old 16.04, 18.04, etc. Dockerfiles, instructions, etc. because it is not totally simple to figure out what is known to work and what is not. FWIW, I think it is fine to say that 18.04 is out.....time to move on, but that is not the impression one gets when looking at the master branch currently.

**Comment by dchansen** [comment]
Fixed on master
