### ISSUE TITLE
Compilation error for master branch

### ISSUE THREAD

**Issue by namgyunlee** [gadgetron/gadgetron#924]
![image](https://user-images.githubusercontent.com/42755584/104866736-20c55580-58f4-11eb-92a8-2cb8630aa001.png)
Could you fix these? 
Thank you!

**Comment by namgyunlee** [comment]
Could you fix this as well?
![image](https://user-images.githubusercontent.com/42755584/104867658-3b98c980-58f6-11eb-935a-88ba6049bb97.png)

**Comment by hansenms** [comment]
I think that is something you can fix yourself by making sure that you have (the right version of) range v3 installed. The current master branch compiles on Ubuntu 18.04 and 20.04. If you would like a recipe for installing the dependencies, please consult https://github.com/gadgetron/gadgetron/blob/master/docker/install_ubuntu_dependencies.sh

**Comment by namgyunlee** [comment]
After running this script install_ubuntu_dependencies.sh, the master branch was successfully compiled. Thank you so much for the fast response!
